### ISSUE TITLE
Question about exports

### ISSUE THREAD

**Issue by Royale06** [SOH69/mm_carkeys#1]
Hello, i wanted to implement the script into a modified esx_vehicleshop with exports and it seems to be not giving me the right key with the car. The plate is correct and the model on the key too but every time i buy a car the key is not working with it. Im using esx with the ox scripts.

Thank you for helping me out.

`RegisterNetEvent('villamos_vehshop:spawnCar', function(coords, model, plate)

    local hash = GetHashKey(model)
    if not IsModelInCdimage(hash) then 
        return print("^1SCRIPT ERROR: Invalid model: "..model)
    end 
    while not HasModelLoaded(hash) do 
        RequestModel(hash)
        Wait(10)
    end 
    local vehicle = CreateVehicle(hash, coords, true, true)
    SetVehicleNumberPlateText(vehicle, plate)
    TaskWarpPedIntoVehicle(PlayerPedId(), vehicle, -1)
    SetModelAsNoLongerNeeded(hash)
    exports.mm_carkeys:GiveKeyItem(plate, vehicle)
end)`

**Comment by SOH69** [comment]
This seems to work fine, get the latest version maybe and report me need to take a look with ox inventory

**Comment by Royale06** [comment]
I'm using the latest version and the problem is still up. It adds the key into my inventory with the correct data but the carkey is not working with the export. I can provide video if you'd like

**Comment by SOH69** [comment]
can you provide me the video with any f8 console error on client/server side

**Comment by Royale06** [comment]
I made a video about buying the car and the aftermath of it. You can watch it on medal by clicking [here](https://medal.tv/games/gta-v/clips/1NfBMAQdj9yHqM/d1337txbUeSf?invite=cr-MSxJTUcsNDc1NDc1MCw).

**Comment by SOH69** [comment]
New ESX fix branch [Release](https://github.com/SOH69/mm_carkeys/tree/esx-test)

**Comment by Royale06** [comment]
Thank you, i will try it and let you know.

**Comment by Royale06** [comment]
So i tested it and now it works perfectly fine, right key, right car. Thank you for helping me out.
